---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: photos
  labels:
    app.kubernetes.io/name: photos
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: web
    app.kubernetes.io/instance: delightfulphotos
